apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: http-producer
  name: http-producer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: http-producer
    spec:
      containers:
        - name: http-producer
          image: scholzj/http-kafka-producer:latest
          env:
            - name: HOSTNAME
              value: my-bridge-bridge-service
            - name: PORT
              value: "8080"
            - name: TOPIC
              value: my-topic
            - name: SEND_INTERVAL
              value: "1000"
            - name: MESSAGE_COUNT
              value: "1000000"
            - name: JAEGER_SERVICE_NAME
              value: http-producer
            - name: JAEGER_AGENT_HOST
              value: my-jaeger-agent
            - name: JAEGER_SAMPLER_TYPE
              value: const
            - name: JAEGER_SAMPLER_PARAM
              value: "1"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: http-consumer
  name: http-consumer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: http-consumer
    spec:
      containers:
        - name: http-consumer
          image: scholzj/http-kafka-consumer:latest
          env:
            - name: HOSTNAME
              value: my-bridge-bridge-service
            - name: PORT
              value: "8080"
            - name: TOPIC
              value: my-topic
            - name: GROUPID
              value: "http-consumer"
            - name: MESSAGE_COUNT
              value: "1000000"
            - name: JAEGER_SERVICE_NAME
              value: http-consumer
            - name: JAEGER_AGENT_HOST
              value: my-jaeger-agent
            - name: JAEGER_SAMPLER_TYPE
              value: const
            - name: JAEGER_SAMPLER_PARAM
              value: "1"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: remusnoc-ptth
  name: remusnoc-ptth
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: remusnoc-ptth
    spec:
      containers:
        - name: remusnoc-ptth
          image: scholzj/http-kafka-consumer:latest
          env:
            - name: HOSTNAME
              value: my-bridge-bridge-service
            - name: PORT
              value: "8080"
            - name: TOPIC
              value: cipot-ym
            - name: GROUPID
              value: remusnoc-ptth
            - name: MESSAGE_COUNT
              value: "1000000"
            - name: JAEGER_SERVICE_NAME
              value: remusnoc-ptth
            - name: JAEGER_AGENT_HOST
              value: my-jaeger-agent
            - name: JAEGER_SAMPLER_TYPE
              value: const
            - name: JAEGER_SAMPLER_PARAM
              value: "1"